### ISSUE TITLE
Tetris Images

### ISSUE THREAD

**Issue by hohaicongthuan** [hohaicongthuan/TETRIS#1]
![etfgersfhstsbxcvrth bdfn tthvtffbsvt](https://user-images.githubusercontent.com/20926690/49714455-7643c880-fc7f-11e8-8c6d-cca864867a58.PNG)

**Comment by hohaicongthuan** [comment]
![fjhcgtyyfvyugkjb](https://user-images.githubusercontent.com/20926690/49856056-898e9980-fe21-11e8-8baa-91213d1cee3f.PNG)

**Comment by AcezukyRockon** [comment]
wow

**Comment by AcezukyRockon** [comment]
o
